export const fuels = ['Diesel', 'Petrol', 'Octane'] as const;
export type Fuel = (typeof fuels)[number];
export const stations = [
  {
    id: 'station-mirpur',
    name: 'Mirpur Fuel Station',
    short: 'Mirpur',
    region: 'Dhaka Division',
    profile: 'Urban high',
    status: 'OPEN',
    inventory: { Diesel: 5600, Petrol: 9200, Octane: 4100 },
    capacity: { Diesel: 15000, Petrol: 14000, Octane: 9000 },
    risk: 'HIGH',
    demand: 'High demand',
    arrival: 'Gazipur · 2 ticks',
  },
  {
    id: 'station-tongi',
    name: 'Tongi Fuel Station',
    short: 'Tongi',
    region: 'Dhaka Division',
    profile: 'Industrial',
    status: 'OPEN',
    inventory: { Diesel: 10500, Petrol: 5200, Octane: 3200 },
    capacity: { Diesel: 18000, Petrol: 9000, Octane: 6000 },
    risk: 'MEDIUM',
    demand: 'Steady demand',
    arrival: 'Gazipur · 2 ticks',
  },
  {
    id: 'station-karnaphuli',
    name: 'Karnaphuli Fuel Station',
    short: 'Karnaphuli',
    region: 'Chattogram Division',
    profile: 'Highway',
    status: 'OPEN',
    inventory: { Diesel: 7800, Petrol: 10800, Octane: 4800 },
    capacity: { Diesel: 14000, Petrol: 15000, Octane: 9000 },
    risk: 'MEDIUM',
    demand: 'Elevated demand',
    arrival: 'Patiya · 2 ticks',
  },
  {
    id: 'station-coxsbazar',
    name: "Cox's Bazar Fuel Station",
    short: "Cox's Bazar",
    region: 'Chattogram Division',
    profile: 'Regional',
    status: 'OPEN',
    inventory: { Diesel: 6500, Petrol: 7000, Octane: 3900 },
    capacity: { Diesel: 12000, Petrol: 12000, Octane: 7000 },
    risk: 'LOW',
    demand: 'Normal demand',
    arrival: 'Patiya · 3 ticks',
  },
];
export const depots = [
  {
    name: 'Gazipur Depot',
    region: 'Dhaka Division',
    status: 'OPEN',
    fill: 68,
    inventory: '131,000 L',
    dispatch: '12,000 L / tick',
    color: 'blue',
  },
  {
    name: 'Patiya Depot',
    region: 'Chattogram Division',
    status: 'CONSTRAINED',
    fill: 54,
    inventory: '121,000 L',
    dispatch: '11,000 L / tick',
    color: 'violet',
  },
];
export const alerts = [
  {
    id: 'ALT-024',
    severity: 'Critical',
    kind: 'Shortage risk',
    title: 'Mirpur diesel projected to stock out',
    detail: 'Inventory 5,600 L · forecast demand 8,500 L/day · 6.2 hours to stockout',
    time: '2 min ago',
    station: 'Mirpur Fuel Station',
    color: 'red',
  },
  {
    id: 'ALT-023',
    severity: 'Warning',
    kind: 'Depot constraint',
    title: 'Patiya depot operating with reduced capacity',
    detail: 'Available dispatch capacity reduced by 25%. Cross-region routes remain available.',
    time: '14 min ago',
    station: 'Patiya Depot',
    color: 'amber',
  },
  {
    id: 'ALT-022',
    severity: 'Warning',
    kind: 'Demand anomaly',
    title: 'Chattogram demand running 18% above baseline',
    detail: 'Elevated demand detected across 2 stations over the last 3 ticks.',
    time: '28 min ago',
    station: 'Chattogram Division',
    color: 'amber',
  },
  {
    id: 'ALT-021',
    severity: 'Info',
    kind: 'Supply arrival',
    title: 'Diesel shipment delayed to Gazipur',
    detail: '18,000 L expected in 3 ticks · was due in 1 tick.',
    time: '43 min ago',
    station: 'Gazipur Depot',
    color: 'blue',
  },
];
export const recommendations = [
  {
    id: 'REC-108',
    station: 'Mirpur Fuel Station',
    stationId: 'station-mirpur',
    fuel: 'Diesel' as Fuel,
    risk: 'HIGH',
    ttf: '6.2 h',
    quantity: '5,000 L',
    source: 'Gazipur Depot',
    route: 'Gazipur → Mirpur',
    eta: '2 ticks · 30 min',
    confidence: 0.86,
    impact: 'Stockout risk 72% → 19%',
    policy: 'Priority allocation',
    why: 'Current inventory covers only 15.8 hours at forecast demand. Demand is 12% above its 7-day baseline.',
    signals: [
      '5,600 L available · 37% of capacity',
      'Forecast demand 8,500 L/day',
      'No incoming shipment on primary route',
    ],
    alternatives: ['Patiya → Mirpur · 4 ticks', 'Defer and review next tick'],
  },
  {
    id: 'REC-107',
    station: 'Karnaphuli Fuel Station',
    stationId: 'station-karnaphuli',
    fuel: 'Petrol' as Fuel,
    risk: 'MEDIUM',
    ttf: '18.4 h',
    quantity: '3,500 L',
    source: 'Patiya Depot',
    route: 'Patiya → Karnaphuli',
    eta: '2 ticks · 30 min',
    confidence: 0.73,
    impact: 'Projected inventory +42%',
    policy: 'FALLBACK POLICY',
    why: 'Demand has stayed above baseline for 3 consecutive ticks. Recommendation generated using the threshold policy while the decision engine is degraded.',
    signals: [
      '10,800 L available · 72% of capacity',
      'Demand anomaly +18%',
      'Patiya dispatch capacity constrained',
    ],
    alternatives: ['Gazipur → Karnaphuli · 4 ticks', 'Review after next simulation tick'],
  },
];
export const routes = [
  {
    id: 'route-gazipur-mirpur',
    from: 'Gazipur Depot',
    to: 'Mirpur',
    ticks: 2,
    max: '7,000 L',
    status: 'AVAILABLE',
  },
  {
    id: 'route-gazipur-tongi',
    from: 'Gazipur Depot',
    to: 'Tongi',
    ticks: 2,
    max: '6,500 L',
    status: 'AVAILABLE',
  },
  {
    id: 'route-patiya-karnaphuli',
    from: 'Patiya Depot',
    to: 'Karnaphuli',
    ticks: 2,
    max: '7,000 L',
    status: 'AVAILABLE',
  },
  {
    id: 'route-patiya-coxsbazar',
    from: 'Patiya Depot',
    to: "Cox's Bazar",
    ticks: 3,
    max: '6,000 L',
    status: 'AVAILABLE',
  },
  {
    id: 'route-gazipur-karnaphuli',
    from: 'Gazipur Depot',
    to: 'Karnaphuli',
    ticks: 4,
    max: '5,000 L',
    status: 'DISRUPTED',
  },
  {
    id: 'route-patiya-mirpur',
    from: 'Patiya Depot',
    to: 'Mirpur',
    ticks: 4,
    max: '5,000 L',
    status: 'AVAILABLE',
  },
];
export const decisions = [
  {
    id: 'DEC-0087',
    tick: 42,
    when: 'Today, 10:42',
    operator: 'A. Rahman',
    action: 'Allocated 4,000 L Petrol',
    route: 'Patiya → Karnaphuli',
    outcome: 'ARRIVED',
    response: 'Allocation #184 · service restored',
  },
  {
    id: 'DEC-0086',
    tick: 41,
    when: 'Today, 10:27',
    operator: 'S. Ahmed',
    action: 'Allocated 3,000 L Diesel',
    route: 'Gazipur → Tongi',
    outcome: 'IN_TRANSIT',
    response: 'Allocation #183 · ETA tick 43',
  },
  {
    id: 'DEC-0085',
    tick: 39,
    when: 'Today, 09:58',
    operator: 'A. Rahman',
    action: 'Rejected 2,000 L Octane',
    route: 'Patiya → Cox’s Bazar',
    outcome: 'REJECTED',
    response: 'Demand normalized · operator review',
  },
];
export const systemEvents = [
  {
    time: '10:44:12',
    level: 'INFO',
    component: 'API Service',
    message: 'Snapshot refreshed from simulator',
    tick: 'Tick 42',
  },
  {
    time: '10:43:58',
    level: 'WARN',
    component: 'Decision Engine',
    message: 'Timeout after 1.5s · fallback policy activated',
    tick: 'Tick 42',
  },
  {
    time: '10:42:03',
    level: 'INFO',
    component: 'Allocation',
    message: 'Allocation #184 confirmed by simulator',
    tick: 'Tick 42',
  },
  {
    time: '10:40:21',
    level: 'WARN',
    component: 'Simulator Client',
    message: 'Stale-data header received · serving last good snapshot',
    tick: 'Tick 41',
  },
];
